### ISSUE TITLE
Doesn't seems to be working anymore. 

### ISSUE THREAD

**Issue by Razzmot** [captaincobbs/ES2-Achievement-Enabler#1]
Does this mod still work with the latest ES2 ?

Since i didn't find any other source for the mod i guessed i could try here. 
Thanks for your time :)

**Comment by NoProblemWithThisAcc** [comment]
I'm new to this one but I just got an achievement unlocked while using mods...

**Comment by captaincobbs** [comment]
I made this immediately after the last update came out, so it should still work

**Comment by Razzmot** [comment]
I suppose i'm doing something wrong... 
Can"t find the relevant sentence in temp file while still finding the one saying steam disabled achievement.
I'll try some more then thanks !

**Comment by captaincobbs** [comment]
Should be fixed now, several people have reported it working.
